#! /usr/bin/perl
#
#	--file <config_file>
#		where <config_file> is the filename of the context config file.
#

use Getopt::Long;
use File::Copy;

print "Entering configure process of YARP log-polar library...\n";

chomp ($ver = `ver`);
chomp ($uname = `uname`);
if (index ($ver, "Windows") < 0 && index ($uname, "CYGWIN") < 0)
{
	print "This is a Windows 2000/XP specific script\n";
	print "Perhaps this procedure can be simply extended to "; 
	print "other OSes but for now, this is all experimental...\n";
	
	die "This script is specific to Windows 2000/XP or Cygwin\n";
}

$yarp_root = $ENV{'YARP_ROOT'};
if (!defined($yarp_root))
{
	die "YARP_ROOT environment variable must be defined!\nto point to the path of the yarp source distribution\n";
}

print "Ready to start...\n";

my $config_file = "$yarp_root/conf/context.conf";
my %options = ();

GetOptions ('file=s' => \$config_file );

if (-e $config_file)
{
	copy ($config_file, "$config_file.old");

	open CONFIG, $config_file or die "Can't open config file $!";

	my $contextual;
	while (<CONFIG>)
	{
		chomp;
		if (/^\[(\w+)\]$/)
		{
			$contextual = $1;
		}
		elsif (/^([A-Za-z0-9_]+)= ?/)
		{
			$options{$contextual."<-".$1} = $';
		}
	}

	close CONFIG;
}

#
#
#

my $os = $options{"Architecture<-OS"};

print "Now I'm going to ask a few questions to help building the configuration. ";
print "For pathnames you can use (type) the pre-defined value \$YARP_ROOT ";
print "that I've verified as: \"$yarp_root\"\n\n";
print "Please, use always the forward slash as a separator!\n";

print "I determined already that you're running on Windows\n";
die "But your configuration file doesn't report so, exiting...\n" unless ($os eq "winnt");

print "Would you like to set a default for library compilation?\n";
get_option_hash ("Compile_Sig_Logpolar<-Lib_Clean", "FALSE", "Clean first: i.e. rebuild libraries?");
get_option_hash ("Compile_Sig_Logpolar<-Lib_Debug", "FALSE", "Debug mode?");
get_option_hash ("Compile_Sig_Logpolar<-Lib_Release", "FALSE", "Release mode (optimization on)?");
get_option_hash ("Compile_Sig_Logpolar<-Lib_Install", "FALSE", "Install after compile?");

# consistency check.
if ($options{"Compile_Sig_Logpolar<-Lib_Debug"} ne "TRUE" && 
	$options{"Compile_Sig_Logpolar<-Lib_Release"} ne "TRUE" && 
	$options{"Compile_Sig_Logpolar<-Lib_Clean"} eq "TRUE")
{
	print "Since you're rebuilding, you should at least select between debug and release\n";
	print "I'm assuming you wanted to compile debug\n";
	$options{"Compile_Sig_Logpolar<-Lib_Debug"} = "TRUE";
}

print "We're done for now, the context file is being updated: \"$config_file\"\n";

#
# uses global value %options
#
sub get_option_hash
{
	my ($key, $default_value, $message) = @_;
	my $line = undef;

	$options{$key} = $default_value if (!exists($options{$key}));

	print "$message [$options{$key}] ";
	chomp($line = <STDIN>);
	$options{$key} = $line if (defined($line) && $line ne '');

	0;
}


#
# creating a new config file.
# 
open CONFIG, "> $config_file";
select CONFIG;

print "//\n";
print "// This is an example of configuration file.\n";
print "// - projects and include files are created relying on this options.\n";
print "//\n";
print "// Generated by <configure.pl>\n";
print "//\n";

my $context = '';
foreach my $key (sort keys %options)
{
	my $value = $options{$key};
	$key =~ /<-/;
	if ($context ne $`)
	{
		$context = $`;
		print "\n[$context]\n";
	}
	print "$'= $value\n";
}

select STDOUT;
close CONFIG;

print "Done!\n";