# Device driver global makefile

ifndef  YARP_ROOT
YARP_ROOT = ../..
endif

include $(YARP_ROOT)/conf/Makefile.template

SUBDIRS = 

all: compile

clean:
	@for d in $(SUBDIRS) ; do \
		( cd $$d ; $(MAKE) clean ); done

install:
	@for d in $(SUBDIRS) ; do \
		( cd $$d ; $(MAKE) install ) ; done

compile:
	@for d in $(SUBDIRS) ; do \
		( cd $$d ; $(MAKE) ); done


