#
# $Id: Makefile.model,v 1.1 2004-12-06 17:11:14 gmetta Exp $
#

ifndef  YARP_ROOT
YARP_ROOT = ../../..
endif

include $(YARP_ROOT)/conf/Makefile.template

MYINCS = -I../include -I../../libYARP_OS/include -I../../libYARP_math/include

include $(YARP_ROOT)/conf/Makefile.src.template
TARGETS += 

