#
# $Id: Makefile,v 1.4 2004-12-06 17:00:31 gmetta Exp $
#

ifndef  YARP_ROOT
YARP_ROOT = ../../..
endif

include $(YARP_ROOT)/conf/Makefile.template

MYINCS = -I../include -I../../libYARP_OS/include -I../../libYARP_math/include

include $(YARP_ROOT)/conf/Makefile.src.template
TARGETS += ../obj/linux/YARPNullGrabberDeviceDriver.o

