#
# $Id: Makefile,v 1.5 2004-12-06 23:26:44 babybot Exp $
#

ifndef  YARP_ROOT
YARP_ROOT = ../../..
endif

include $(YARP_ROOT)/conf/Makefile.template

MYINCS = -I../include -I../../libYARP_OS/include -I../../libYARP_math/include

include $(YARP_ROOT)/conf/Makefile.src.template
TARGETS += ../obj/qnx6/YARPGalilDeviceDriver.o ../obj/qnx6/YARPNullGrabberDeviceDriver.o ../obj/qnx6/YARPPicoloDeviceDriver.o 

