
RUN = run
INACTIVE = $(wildcard *.$(RUN))
ACTIVE = $(patsubst %.$(RUN), %.o, $(INACTIVE))

%.o: %.$(RUN)
	$<
	echo Done > $@

all:
	echo Please specify a target

depend:
	# need to be on a unix machine for this
	makedepend *.$(RUN)
	sed "s/\.$(RUN)/\.o/g" < Makefile > Makefile.new
	mv Makefile.new Makefile

clean:
	{ mv $(ACTIVE) backup 2> /dev/null; } || echo -n

# DO NOT DELETE

attention.o: dpramd.o meid.o
