# Application global makefile

all: install

clean:
	+cd ./color_segm; make $(@F)
	+cd ./optic_flow; make $(@F)
	+cd ./visual_attn; make $(@F)
	+cd ./skin; make $(@F)
	+cd ./disparity; make $(@F)
	+cd ./attention; make $(@F)
	+cd ./face_finder; make $(@F)
	+cd ./face_tracker; make $(@F)
	+cd ./headcontrol/src/default; make $(@F)
	+cd ./armcontrol/src/default; make $(@F)
	+cd ./msg/src/default; make $(@F)
	+cd ./of; make $(@F)
	+cd ./arm_tracker; make $(@F)
#	+cd ./recognizer; make $(@F)

install: 
	+cd ./color_segm; make $(@F)
	+cd ./optic_flow; make $(@F)
	+cd ./visual_attn; make $(@F)
	+cd ./skin; make $(@F)
	+cd ./disparity; make $(@F)
	+cd ./attention; make $(@F)
	+cd ./face_finder; make $(@F)
	+cd ./face_tracker; make $(@F)
	+cd ./headcontrol/src/default; make $(@F)
	+cd ./armcontrol/src/default; make $(@F)
	+cd ./msg/src/default; make $(@F)
	+cd ./of; make $(@F)
	+cd ./arm_tracker; make $(@F)
#	+cd ./recognizer; make $(@F)
