#ifndef __APPCONFIG_H
#define __APPCONFIG_H

/*****************************************************************************
*
* Include needed SDK components below by changing #undef to #define.
* Refer to ../config/config.h for complete list of all components and
* component default initialization.
*
*****************************************************************************/

#define  INCLUDE_DSPFUNC      /* DSP Function library */


#endif
