/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : Cpu.C
**     Project   : controller_y
**     Processor : 56F807
**     Beantype  : 56F807
**     Version   : Bean 01.002, Driver 01.05, CPU db: 2.71.191
**     Compiler  : Metrowerks DSP C Compiler
**     Date/Time : 1/20/2005, 12:49 PM
**     Abstract  :
**
**     Settings  :
**
**     Contents  :
**         GetSpeedMode - byte Cpu_GetSpeedMode(void);
**         EnableInt    - void Cpu_EnableInt(void);
**         DisableInt   - void Cpu_DisableInt(void);
**         SetWaitMode  - void Cpu_SetWaitMode(void);
**         SetStopMode  - void Cpu_SetStopMode(void);
**         SetDataMode  - void Cpu_SetDataMode(byte Mode);
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2002
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/

/* MODULE Cpu. */
#include "AS1.h"
#include "CAN1.h"
#include "QD1.h"
#include "QD2.h"
#include "IFsh1.h"
#include "PWMC1.h"
#include "PWMC2.h"
#include "TI1.h"
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Events.h"
#include "Cpu.h"


/* Global variables */
volatile word SR_lock=0;               /* Lock */
volatile word SR_reg;                  /* Current value of the SR reegister */

/*
** ===================================================================
**     Method      :  Cpu_Interrupt (bean 56F807)
**
**     Description :
**         This method is internal. It is used by Processor Expert
**         only.
** ===================================================================
*/
#pragma interrupt
void Cpu_Interrupt(void)
{
}

/*
** ===================================================================
**     Method      :  Cpu_DisableInt (bean 56F807)
**
**     Description :
**         Disable all maskable interrupts
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_DisableInt(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_EnableInt (bean 56F807)
**
**     Description :
**         Enable all maskable interrupts
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_EnableInt(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_SetStopMode (bean 56F807)
**
**     Description :
**         Set low power mode - Stop mode.
**         For more information about the stop mode see
**         documentation of this CPU.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_SetStopMode(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_SetWaitMode (bean 56F807)
**
**     Description :
**         Set low power mode - Wait mode.
**         For more information about the wait mode see
**         documentation of this CPU.
**         Release from wait mode: Reset or interrupt
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_SetWaitMode(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_SetDataMode (bean 56F807)
**
**     Description :
**         Set the Data memory map to use either internal & external
**         resources or external resources only.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Mode            - Data memory access mode.
**                           Possible modes:
**                           INT_EXT_MODE - use internal & external
**                           resources
**                           EXT_MODE - use external resources only
**     Returns     : Nothing
** ===================================================================
*/
void Cpu_SetDataMode(byte Mode)
{
  if (Mode == INT_EXT_MODE)
    asm { bfclr  #0x0008,OMR }         /* Set internal and external data memory mode */
  else
    asm { bfset  #0x0008,OMR }         /* Set external data memory mode */
}

/*
** ===================================================================
**     Method      :  Cpu_GetSpeedMode (bean 56F807)
**
**     Description :
**         Get current speed mode
**     Parameters  : None
**     Returns     :
**         ---             - Speed mode (HIGH_SPEED, LOW_SPEED,
**                           SLOW_SPEED)
** ===================================================================
*/
byte Cpu_GetSpeedMode(void)
{
  return HIGH_SPEED;                   /* Result the actual cpu mode - high speed mode*/
}

#if 0
/*
** ===================================================================
**     Method      :  _EntryPoint (bean 56F807)
**
**     Description :
**         This method is internal. It is used by Processor Expert
**         only.
** ===================================================================
*/
extern void init_56800_(void);         /* Forward declaration of external startup function declared in file FSTART.ASM */
void _EntryPoint(void)
{
  /*** ### 56F807 "Cpu" init code ... ***/
  /*** PE initialization code after reset ***/
  /* System clock initialization */
  setRegBit(PLLCR, PLLPD);             /* Disable PLL */
  setReg(PLLDB, 19);                   /* Set the clock prescalers */
  setRegBit(PLLCR, LCKON);             /* Enable lock detector */
  clrRegBit(PLLCR, PLLPD);             /* Enable PLL */
  while(!getRegBit(PLLSR, LCK0)){}     /* Wait for PLL lock */
  setRegBitGroup(PLLCR, ZSRC, 2);      /* Select clock source from postscaler */
  /*** End of PE initialization code after reset ***/

  asm(JMP init_56800_);                /* Jump to C startup code */
}

#endif

/*
** ===================================================================
**     Method      :  PE_low_level_init (bean 56F807)
**
**     Description :
**         This method is internal. It is used by Processor Expert
**         only.
** ===================================================================
*/
void PE_low_level_init(void)
{
  setReg(SYS_CNTL, 0);                 /* Enable/Disable pullup registers for the given devices */
  setRegBitGroup(DEC0_DECCR,MODE, 0);  /* Set up Switch Matrix 0 mode */
  setReg(DEC0_FIR,0);                  /* Set up Filter Interval Register of Quadrature Decoder 0 */
  setRegBitGroup(DEC1_DECCR,MODE, 0);  /* Set up Switch Matrix 1 mode  */
  setReg(DEC1_FIR,0);                  /* Set up Filter Interval Register of Quadrature Decoder 1 */
  /* Common initialization of the CPU registers */
/* GPIO_E_PER: PE=3 */
  output( GPIO_E_PER, input( GPIO_E_PER ) | 3 );
/* IPR: CH3=1 */
  output( IPR, input( IPR ) | 4096 );
/* GPR3: PLR15=4,PLR14=4 */
  output( GPR3, input( GPR3 ) & ~13056 | 17408 );
/* GPR4: PLR17=4,PLR16=4 */
  output( GPR4, input( GPR4 ) & ~51 | 68 );
/* GPR10: PLR42=4 */
  output( GPR10, input( GPR10 ) & ~768 | 1024 );
  /* ### 56F807 "Cpu" init code ... */
  /* ### Asynchro serial "AS1" init code ... */
  clrRegBits(GPIO_E_DDR, 2);           /* Set input direction of the RxD pin */
  setRegBits(GPIO_E_DR, 1);            /* Set high level of the TxD pin */
  setRegBits(GPIO_E_DDR, 1);           /* Set output direction of the TxD pin */
  AS1_Init();
  /* ###  "CAN1" init code ... */
  CAN1_Init();
  /* ### QuadratureDecoder "QD1" init code ... */
  QD1_Init();
  /* ### QuadratureDecoder "QD2" init code ... */
  QD2_Init();
  /* ### PWMMC "PWMC1" init code ... */
  PWMC1_Init();
  /* ### PWMMC "PWMC2" init code ... */
  PWMC2_Init();
  /* ### TimerInt "TI1" init code ... */
  TI1_Init();
  __EI();                              /* Enable interrupts */
}

/* END Cpu. */

/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 03.32 for 
**     the Motorola 56800 series of microcontrollers.
**
** ###################################################################
*/
