/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : PWMC1.C
**     Project   : controller_y
**     Processor : 56F807
**     Beantype  : PWMMC
**     Version   : Bean 01.235, Driver 01.06, CPU db: 2.71.191
**     Compiler  : Metrowerks DSP C Compiler
**     Date/Time : 12/14/2004, 2:50 PM
**     Abstract  :
**         This bean "PWMMC" implements 6-channel center-aligned or 
**         edge-aligned pulse-width modulator for AC motor control, which 
**         is presented on chip. The device is capable of controlling most 
**         motor types: AC induction motors (ACIM), both brushless (BLDC) 
**         and brush DC motors (BDC), switched (SRM) and variable reluctance  
**         motors (VRM),and stepper motors.
**         Another possibility of using this bean is as a pulse-width modulation 
**         generator that generates 6 signals with variable duty and fixed cycle.
**     Settings  :
**         Used output pins            : 
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       75            |  PWMA0
**                       77            |  PWMA1
**                       78            |  PWMA2
**                       79            |  PWMA3
**                       80            |  PWMA4
**                       81            |  PWMA5
**             ----------------------------------------------------
**
**         Device                      : PWM_A [15-bit] 
**
**         Counter                     : PWMA_PMCNT [4612]
**         Mode register               : PWMA_PMCFG [61775]
**         Run register                : PWMA_PMCTL [4608]
**         Prescaler                   : PWMA_PMCTL [4608]
**         Modulo register             : PWMA_PWMCM [61765]
**         Compare 0 register          : PWMA_PWMVAL0 [4614]
**         Compare 1 register          : PWMA_PWMVAL1 [4615]
**         Compare 2 register          : PWMA_PWMVAL2 [4616]
**         Compare 3 register          : PWMA_PWMVAL3 [4617]
**         Compare 4 register          : PWMA_PWMVAL4 [4618]
**         Compare 5 register          : PWMA_PWMVAL5 [4619]
**         Fault Control register      : PWMA_PMFCTL [61761]
**         Fault Status register       : PWMA_PMFSA [61762]
**         Fault Acknowledge register  : PWMA_PMFSA [61762]
**         Output Control register     : PWMA_PMOUT [61763]
**         Dead-Time register          : PWMA_PMDEADTM [61772]
**         Disable Mapping register  1 : PWMA_PMDISMAP1 [61773]
**         Disable Mapping register  2 : PWMA_PMDISMAP2 [61774]
**         Channel Control register    : PWMA_PMCCR [61776]
**         Port register               : PWMA_PMPORT [61777]
**
**         User handling procedure     : not specified
**
**
**         Initialization:
** Align                               : edge-aligned mode
** Mode of PWM pair 0                  : complementary
** Mode of PWM pair 1                  : complementary
** Mode of PWM pair 2                  : complementary
** Top-side PWM pair 0 polarity        : positive
** Top-side PWM pair 1 polarity        : positive
** Top-side PWM pair 2 polarity        : positive
** Bottom-side PWM pair 0 polarity     : positive
** Bottom-side PWM pair 1 polarity     : positive
** Bottom-side PWM pair 2 polarity     : positive
** Write protect                       : no
** Output                              : Disabled
** Reload                              : every 1 PWM cycle
** Half cycle reload                   : no
** Hardware acceleration               : disabled
** Dead Time
**  High-speed CPU mode
**    Prescaler                        : divide-by-40
**    Clock                            : 1000000 Hz 
**    Xtal ticks                       : 8  
**    microseconds                     : 1 
**    seconds (real)                   : 0.0000010 
**
** Output control channel 0            : Disabled
** Output control channel 1            : Disabled
** Output control channel 2            : Disabled
** Output control channel 3            : Disabled
** Output control channel 4            : Disabled
** Output control channel 5            : Disabled
**
** Correction
**   Correction method                 : method 1
**   PWM pair 0                        : top
**   PWM pair 1                        : top
**   PWM pair 2                        : top
**
**   Channel masks
**     Mask channel 0                  : no
**     Mask channel 1                  : no
**     Mask channel 2                  : no
**     Mask channel 3                  : no
**     Mask channel 4                  : no
**     Mask channel 5                  : no
**
** Fault device 1
**   clearing mode                     : automatic
**   pin                               : FAULTA0
** Fault device 2
**   clearing mode                     : automatic
**   pin                               : FAULTA1
** Fault device 3
**   clearing mode                     : automatic
**   pin                               : FAULTA2
** Fault device 4
**   clearing mode                     : automatic
**   pin                               : FAULTA3
**
** Mask fault pins
** Channel 0
**   Mask fault 1                      : yes
**   Mask fault 2                      : yes
**   Mask fault 3                      : yes
**   Mask fault 4                      : yes
** Channel 1
**   Mask fault 1                      : yes
**   Mask fault 2                      : yes
**   Mask fault 3                      : yes
**   Mask fault 4                      : yes
** Channel 2
**   Mask fault 1                      : yes
**   Mask fault 2                      : yes
**   Mask fault 3                      : yes
**   Mask fault 4                      : yes
** Channel 3
**   Mask fault 1                      : yes
**   Mask fault 2                      : yes
**   Mask fault 3                      : yes
**   Mask fault 4                      : yes
** Channel 4
**   Mask fault 1                      : yes
**   Mask fault 2                      : yes
**   Mask fault 3                      : yes
**   Mask fault 4                      : yes
** Channel 5
**   Mask fault 1                      : yes
**   Mask fault 2                      : yes
**   Mask fault 3                      : yes
**   Mask fault 4                      : yes
**
**  Device                             : Enabled
**  Event                              : Enabled
**  High-speed CPU mode
**    Prescaler                        : divide-by-1
**    Clock                            : 40000000 Hz
**    Unit                              Xtal ticks
**      Period                         : 267  
**      Channel 0 pulse width          : 133
**      Channel 1 pulse width          : 133
**      Channel 2 pulse width          : 0
**      Channel 3 pulse width          : 266
**      Channel 4 pulse width          : 0
**      Channel 5 pulse width          : 266
**    Unit                              microseconds
**      Period                         : 33 
**      Channel 0 pulse width          : 17
**      Channel 1 pulse width          : 17
**      Channel 2 pulse width          : 0
**      Channel 3 pulse width          : 33
**      Channel 4 pulse width          : 0
**      Channel 5 pulse width          : 33
**    Unit                              seconds (real)
**      Period                         : 0.0000333 
**      Channel 0 pulse width          : 0.0000167
**      Channel 1 pulse width          : 0.0000167
**      Channel 2 pulse width          : 0.0000000
**      Channel 3 pulse width          : 0.0000333
**      Channel 4 pulse width          : 0.0000000
**      Channel 5 pulse width          : 0.0000333
**
**     Contents  :
**         Enable           - byte PWMC1_Enable(void);
**         Disable          - byte PWMC1_Disable(void);
**         SetDuty          - byte PWMC1_SetDuty(byte channel,int duty);
**         SetDutyPercent   - byte PWMC1_SetDutyPercent(byte channel,byte duty);
**         Load             - void PWMC1_Load(void);
**         OutputPadEnable  - void PWMC1_OutputPadEnable(void);
**         OutputPadDisable - void PWMC1_OutputPadDisable(void);
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2002
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/


/* MODULE PWMC1. */

#include "PWMC1.h"

static bool EnUser;                    /* Enable/Disable device by user */

/*
** ===================================================================
**     Method      :  PWMC1_HWEnDi (bean PWMMC)
**
**     Description :
**         This method is internal. It is used by Processor Expert
**         only.
** ===================================================================
*/
static void HWEnDi(void)
{
  if (EnUser) {                        /* Enable device? */
    setRegBits(PWMA_PMCTL,3);          /* Load counter and modulo registers into buffers and run counter */
  }
  else {                               /* Disable device? */
    clrRegBit(PWMA_PMCTL,PWMEN);       /* Stop counter */
  }
}
/*
** ===================================================================
**     Method      :  PWMC1_Enable (bean PWMMC)
**
**     Description :
**         Enable the bean - it starts the signal generation. Events
**         can be disabled/enabled by DisableEvent/EnableEvent.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte PWMC1_Enable(void)
{
  if (!EnUser) {                       /* Is the device disabled by user? */
    EnUser = TRUE;                     /* If yes then set the flag "device enabled" */
    HWEnDi();                          /* Enable the device */
  }
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  PWMC1_Disable (bean PWMMC)
**
**     Description :
**         Disable the bean - it stops signal generation and events
**         calling. When the timer is disabled, it is possible to
**         call method "SetOutput" to control the output value on
**         corresponding pin.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte PWMC1_Disable(void)
{
  if (EnUser) {                        /* Is the device enabled by user? */
    EnUser = FALSE;                    /* If yes then set the flag "device disabled" */
    HWEnDi();                          /* Disable the device */
  }
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  PWMC1_Init (bean PWMMC)
**
**     Description :
**         This method is internal. It is used by Processor Expert
**         only.
** ===================================================================
*/
void PWMC1_Init(void)
{
  /* PWMA_PMCTL: LDFQ=0,HALF=0,IPOL2=0,IPOL1=0,IPOL0=0,PRSC=0,PWMRIE=0,PWMF=0,ISENS=0,LDOK=0,PWMEN=0 */
  setReg(PWMA_PMCTL,0);                /* Set up PWM control register */
  /* PWMA_PMFCTL: FIE3=0,FMODE3=1,FIE2=0,FMODE2=1,FIE1=0,FMODE1=1,FIE0=0,FMODE0=1 */
  setReg(PWMA_PMFCTL,85);              /* Set up Fault Control Register*/
  /* PWMA_PMDISMAP1: DISMAP=0 */
  setReg(PWMA_PMDISMAP1,0);            /* Set up PWM Disable Mapping Register 1 */
  /* PWMA_PMDISMAP2: DISMAP7=0,DISMAP6=0,DISMAP5=0,DISMAP4=0,DISMAP3=0,DISMAP2=0,DISMAP1=0,DISMAP0=0 */
  setReg(PWMA_PMDISMAP2,0);            /* Set up PWM Disable Mapping Register 2 */
  /* PWMA_PMOUT: PAD_EN=0,??=0,OUTCTL=0,??=0,??=0,OUT=0 */
  setReg(PWMA_PMOUT,0x0000);           /* Set up Output Control Register */
  /* PWMA_PMCCR: ENHA=0,??=0,MSK=0,??=0,??=0,VLMODE=0,??=0,SWP45=0,SWP23=0,SWP01=0 */
  setReg(PWMA_PMCCR,0x0000);           /* Set up PWM Channel Control Register */
  /* PWMA_PMCFG: ??=0,??=0,??=0,EDG=1,??=0,TOPNEG45=0,TOPNEG23=0,TOPNEG01=0,??=0,BOTNEG45=0,BOTNEG23=0,BOTNEG01=0,INDEP45=0,INDEP23=0,INDEP01=0,WP=0 */
  setReg(PWMA_PMCFG,4096);             /* Set up PWM configure register */
  EnUser = TRUE;                       /* Enable device */
  setReg(PWMA_PMDEADTM,40);            /* Set up Dead-Time Register */
  setReg(PWMA_PWMVAL0,666);            /* Store initial value to the duty-compare register */
  setReg(PWMA_PWMVAL1,667);            /* Store initial value to the duty-compare register */
  setReg(PWMA_PWMVAL2,1);              /* Store initial value to the duty-compare register */
  setReg(PWMA_PWMVAL3,1332);           /* Store initial value to the duty-compare register */
  setReg(PWMA_PWMVAL4,1);              /* Store initial value to the duty-compare register */
  setReg(PWMA_PWMVAL5,1332);           /* Store initial value to the duty-compare register */
  setReg(PWMA_PWMCM,1333);             /* and to the period-modulo register */
  HWEnDi();                            /* Enable/disable device according to status flags */
}

/*
** ===================================================================
**     Method      :  PWMC1_SetDuty (bean PWMMC)
**
**     Description :
**         Setting duty(value) register of selected channel.  The
**         value is loaded after calling Load() method.
**     Parameters  :
**         NAME            - DESCRIPTION
**         channel         - channel 0-5
**         duty            - Duty value for selected channel.
**                           Writing a number less than or equal to 0
**                           causes the PWM to be off for the entire
**                           PWM period. Writing a number greater
**                           than or equal to the 15 bit (12-bit on
**                           HC08MR32 CPU) modulus causes the PWM to
**                           be on for the entire PWM period.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_NOTAVAIL - Channel is disabled
**                           ERR_RANGE - Parameter channel is out of
**                           range
** ===================================================================
*/
byte PWMC1_SetDuty(byte channel,int duty)
{
  switch (channel) {
  case 0 :
      setReg(PWMA_PWMVAL0,duty);       /* Store value to the duty-compare register 0 */
      break;
  case 1 :
      setReg(PWMA_PWMVAL1,duty);       /* Store value to the duty-compare register 1 */
      break;
  case 2 :
      setReg(PWMA_PWMVAL2,duty);       /* Store value to the duty-compare register 2 */
      break;
  case 3 :
      setReg(PWMA_PWMVAL3,duty);       /* Store value to the duty-compare register 3 */
      break;
  case 4 :
      setReg(PWMA_PWMVAL4,duty);       /* Store value to the duty-compare register 4 */
      break;
  case 5 :
      setReg(PWMA_PWMVAL5,duty);       /* Store value to the duty-compare register 5 */
      break;
  default: return ERR_RANGE;
  }
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  PWMC1_SetDutyPercent (bean PWMMC)
**
**     Description :
**         Setting duty(value) in percent of selected channel.  The
**         value is loaded after calling Load() method.
**     Parameters  :
**         NAME            - DESCRIPTION
**         channel         - channel 0-5
**         duty            - Duty value in pecents for selected
**                           channel.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_NOTAVAIL - Channel is disabled
**                           ERR_RANGE - Parameter channel is out of
**                           range
** ===================================================================
*/
byte PWMC1_SetDutyPercent(byte channel,byte duty)
{
  register word dutyreg;

  if (duty>100)
    return ERR_RANGE;
  dutyreg = (long)getReg(PWMA_PWMCM)*duty/100; /* Calculate real duty from percent value */
  switch (channel) {
  case 0 :
      setReg(PWMA_PWMVAL0,dutyreg);    /* Store percent duty value to the duty-compare register 0 */
      break;
  case 1 :
      setReg(PWMA_PWMVAL1,dutyreg);    /* Store percent duty value to the duty-compare register 1 */
      break;
  case 2 :
      setReg(PWMA_PWMVAL2,dutyreg);    /* Store percent duty value to the duty-compare register 2 */
      break;
  case 3 :
      setReg(PWMA_PWMVAL3,dutyreg);    /* Store percent duty value to the duty-compare register 3 */
      break;
  case 4 :
      setReg(PWMA_PWMVAL4,dutyreg);    /* Store percent duty value to the duty-compare register 4 */
      break;
  case 5 :
      setReg(PWMA_PWMVAL5,dutyreg);    /* Store percent duty value to the duty-compare register 5 */
      break;
  default: return ERR_RANGE;
  }
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  PWMC1_Load (bean PWMMC)
**
**     Description :
**         Apply last seting of the methods SetDuty, SetDutyPercent,
**         SetPeriod and SetPrescaler.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void PWMC1_Load(void)

**  This method is implemented as a macro. See PWMC1.h file.  **

*/

/*
** ===================================================================
**     Method      :  PWMC1_OutputPadEnable (bean PWMMC)
**
**     Description :
**         Method enables output pads.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void PWMC1_OutputPadEnable(void)

**  This method is implemented as a macro. See PWMC1.h file.  **

*/

/*
** ===================================================================
**     Method      :  PWMC1_OutputPadDisable (bean PWMMC)
**
**     Description :
**         Method disables output pads.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void PWMC1_OutputPadDisable(void)

**  This method is implemented as a macro. See PWMC1.h file.  **

*/

/* END PWMC1. */

/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 03.32 for 
**     the Motorola 56800 series of microcontrollers.
**
** ###################################################################
*/
