/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : QD1.C
**     Project   : controller_y
**     Processor : 56F807
**     Beantype  : QuadratureDecoder
**     Version   : Bean 01.020, Driver 01.04, CPU db: 2.71.191
**     Compiler  : Metrowerks DSP C Compiler
**     Date/Time : 12/14/2004, 2:54 PM
**     Abstract  :
**         Quadrature decoder module is used to decode shaft position, revolution 
**         count and speed. Each quadrature decoder module has four input signals: 
**         PHASEA, PHASEB, INDEX, and HOME which are connected to the quadrature 
**         encoder. 
**     Settings  :
**         Used output pins            :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       147           |  PHASEA0_TA0
**                       148           |  PHASEB0_TA1
**                       149           |  INDEX0_TA2
**                       150           |  HOME0_TA3
**             ----------------------------------------------------
**         Device                      : Quad_Decoder0
**
**         Decoder Control Reg.        : DEC0_DECCR [61824]
**         Filter Interval Reg.        : DEC0_FIR  [61825]
**         Watchdog Timeout Reg.       : DEC0_WTR  [61826]
**         Position Differ. Count Reg. : DEC0_POSD [61827]
**         Position Differ. Hold Reg.  : DEC0_POSDH [61828]
**         Revolution Counter Reg.     : DEC0_REV  [61829]
**         Revolution Hold Reg.        : DEC0_REVH [61830]
**         Upper Position Counter Reg. : DEC0_UPOS [61831]
**         Lower Position Counter Reg. : DEC0_LPOS [61832]
**         Upper Position Hold Reg.    : DEC0_UPOSH [61833]
**         Lower Position Hold Reg.    : DEC0_LPOSH [61834]
**         Upper Initialization Reg.   : DEC0_UIR  [61835]
**         Lower Initialization Reg.   : DEC0_LIR  [61836]
**         Input Monitor Reg.          : DEC0_IMR  [61837]
**         User handling procedure     : not specified
**         User handling procedure     : not specified
**         User handling procedure     : not specified
**
**         Home edge                   : positive edge
**         Home initialization         : no
**         Index edge                  : positive edge
**         Index initialization        : no
**         Bypass decoder logic        : no
**         Reverse counting            : no
**
**         Initialization:
**              Event                  : Enabled
**
**         Watchdog timer              : Disabled
**     Contents  :
**         SetPosition  - byte QD1_SetPosition(dword Position);
**         GetPosition  - byte QD1_GetPosition(dword *Position);
**         InitPosition - byte QD1_InitPosition(void);
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2002
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/


/* MODULE QD1. */

#include "dspfunc.h"
#include "prototype.h"
#include "QD1.h"

/*
** ===================================================================
**     Method      :  QD1_SetPosition (bean QuadratureDecoder)
**
**     Description :
**         This method sets position counter.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Position        - Value stored in position
**                           counter.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte QD1_SetPosition(dword Position)
{
  setReg(DEC0_UPOS,(word)(Position<<16)); /* Set Upper Position Counter Register */
  setReg(DEC0_LPOS,(word)(Position));  /* Set Lower Position Counter Register */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  QD1_GetPosition (bean QuadratureDecoder)
**
**     Description :
**         This method gets position counter. Position value is
**         captured toi the difference hold register and difference
**         counter is cleared.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Position        - Pointer to value stored in
**                           position counter.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte QD1_GetPosition(dword *Position)
{
  *Position = getReg(DEC0_LPOS)|(dword)getReg(DEC0_UPOSH<<16); /* Get Lower hold and Upper Position Counter Registers */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  QD1_Init (bean QuadratureDecoder)
**
**     Description :
**         This method is internal. It is used by Processor Expert
**         only.
** ===================================================================
*/
void QD1_Init(void)
{
  /* DEC0_DECCR: HIRQ=0,HIE=0,HIP=0,HNE=0,SWIP=0,REV=0,PH1=0,XIRQ=0,XIE=0,XIP=0,XNE=0,DIRQ=0,DIE=0,WDE=0,MODE=0 */
  setRegBits(DEC0_DECCR,0);            /* Set up Decoder Control Register */
}

/*
** ===================================================================
**     Method      :  QD1_InitPosition (bean QuadratureDecoder)
**
**     Description :
**         This method triggers initialization of position counter
**         from position initialization register.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte QD1_InitPosition(void)
{
  setRegBit(DEC0_DECCR,SWIP);          /* Set SWIP bit to trigger initialization of the position counter */
  return ERR_OK;                       /* OK */
}

/* END QD1. */

/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 03.32 for 
**     the Motorola 56800 series of microcontrollers.
**
** ###################################################################
*/
