/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : QD2.C
**     Project   : controller_y
**     Processor : 56F807
**     Beantype  : QuadratureDecoder
**     Version   : Bean 01.020, Driver 01.04, CPU db: 2.71.191
**     Compiler  : Metrowerks DSP C Compiler
**     Date/Time : 1/20/2005, 12:49 PM
**     Abstract  :
**         Quadrature decoder module is used to decode shaft position, revolution 
**         count and speed. Each quadrature decoder module has four input signals: 
**         PHASEA, PHASEB, INDEX, and HOME which are connected to the quadrature 
**         encoder. 
**     Settings  :
**         Used output pins            :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       151           |  PHASEA1_TB0
**                       152           |  PHASEB1_TB1
**                       154           |  INDEX1_TB2
**                       155           |  HOME1_TB3
**             ----------------------------------------------------
**         Device                      : Quad_Decoder1
**
**         Decoder Control Reg.        : DEC1_DECCR [61840]
**         Filter Interval Reg.        : DEC1_FIR  [61841]
**         Watchdog Timeout Reg.       : DEC1_WTR  [61842]
**         Position Differ. Count Reg. : DEC1_POSD [61843]
**         Position Differ. Hold Reg.  : DEC1_POSDH [61844]
**         Revolution Counter Reg.     : DEC1_REV  [61845]
**         Revolution Hold Reg.        : DEC1_REVH [61846]
**         Upper Position Counter Reg. : DEC1_UPOS [61847]
**         Lower Position Counter Reg. : DEC1_LPOS [61848]
**         Upper Position Hold Reg.    : DEC1_UPOSH [61849]
**         Lower Position Hold Reg.    : DEC1_LPOSH [61850]
**         Upper Initialization Reg.   : DEC1_UIR  [61851]
**         Lower Initialization Reg.   : DEC1_LIR  [61852]
**         Input Monitor Reg.          : DEC1_IMR  [61853]
**         User handling procedure     : not specified
**         User handling procedure     : not specified
**         User handling procedure     : not specified
**
**         Home edge                   : positive edge
**         Home initialization         : no
**         Index edge                  : positive edge
**         Index initialization        : no
**         Bypass decoder logic        : no
**         Reverse counting            : no
**
**         Initialization:
**              Event                  : Enabled
**
**         Watchdog timer              : Disabled
**     Contents  :
**         SetPosition  - byte QD2_SetPosition(dword Position);
**         GetPosition  - byte QD2_GetPosition(dword *Position);
**         InitPosition - byte QD2_InitPosition(void);
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2002
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/


/* MODULE QD2. */

#include "dspfunc.h"
#include "prototype.h"
#include "QD2.h"

#if 0
/*
** ===================================================================
**     Method      :  QD2_SetPosition (bean QuadratureDecoder)
**
**     Description :
**         This method sets position counter.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Position        - Value stored in position
**                           counter.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte QD2_SetPosition(dword Position)
{
  setReg(DEC1_UPOS,(word)(Position<<16)); /* Set Upper Position Counter Register */
  setReg(DEC1_LPOS,(word)(Position));  /* Set Lower Position Counter Register */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  QD2_GetPosition (bean QuadratureDecoder)
**
**     Description :
**         This method gets position counter. Position value is
**         captured toi the difference hold register and difference
**         counter is cleared.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Position        - Pointer to value stored in
**                           position counter.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte QD2_GetPosition(dword *Position)
{
  *Position = getReg(DEC1_LPOS)|(dword)getReg(DEC1_UPOSH<<16); /* Get Lower hold and Upper Position Counter Registers */
  return ERR_OK;                       /* OK */
}
#endif

/*
** ===================================================================
**     Method      :  QD2_Init (bean QuadratureDecoder)
**
**     Description :
**         This method is internal. It is used by Processor Expert
**         only.
** ===================================================================
*/
void QD2_Init(void)
{
  /* DEC1_DECCR: HIRQ=0,HIE=0,HIP=0,HNE=0,SWIP=0,REV=0,PH1=0,XIRQ=0,XIE=0,XIP=0,XNE=0,DIRQ=0,DIE=0,WDE=0,MODE=0 */
  setRegBits(DEC1_DECCR,0);            /* Set up Decoder Control Register */
}

/*
** ===================================================================
**     Method      :  QD2_InitPosition (bean QuadratureDecoder)
**
**     Description :
**         This method triggers initialization of position counter
**         from position initialization register.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte QD2_InitPosition(void)
{
  setRegBit(DEC1_DECCR,SWIP);          /* Set SWIP bit to trigger initialization of the position counter */
  return ERR_OK;                       /* OK */
}

/* END QD2. */

/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 03.32 for 
**     the Motorola 56800 series of microcontrollers.
**
** ###################################################################
*/
