#
# $Id: Makefile.model,v 1.2 2004-12-08 01:06:02 gmetta Exp $
#

ifndef  YARP_ROOT
YARP_ROOT = ../../..
endif

include $(YARP_ROOT)/conf/Makefile.template

MYINCS = -I../include -I../../libYARP_OS/include -I../../libYARP_math/include
MYCODELIB = libYARP_robot

include $(YARP_ROOT)/conf/Makefile.src.template
TARGETS +=

