#
# $Id: Makefile.model,v 1.2 2004-12-08 01:06:01 gmetta Exp $
#

ifndef  YARP_ROOT
YARP_ROOT = ../..
endif

MYCODELIB = libYARP_robot
include $(YARP_ROOT)/conf/Makefile.template

SUBDIRS = 

all: target

target:
	@for d in $(SUBDIRS) ; do \
		( cd $$d ; $(MAKE) target ); done

clean:
	@for d in $(SUBDIRS) ; do \
		( cd $$d ; $(MAKE) clean ); done

install:
	@for d in $(SUBDIRS) ; do \
		( cd $$d ; $(MAKE) install ) ; done


