#
# $Id: Makefile.model,v 1.1 2004-12-07 15:44:53 babybot Exp $
#

ifndef  YARP_ROOT
YARP_ROOT = ../..
endif

include $(YARP_ROOT)/conf/Makefile.template

SUBDIRS = 

all: target

target:
	@for d in $(SUBDIRS) ; do \
		( cd $$d ; $(MAKE) target ); done

clean:
	@for d in $(SUBDIRS) ; do \
		( cd $$d ; $(MAKE) clean ); done

install:
	@for d in $(SUBDIRS) ; do \
		( cd $$d ; $(MAKE) install ) ; done


