
ifndef  YARP_ROOT
YARP_ROOT = ../../..
endif

include $(YARP_ROOT)/conf/Makefile.tool.template

CDEFS += -I /usr/lib/gtk-2.0/include -I /usr/lib/glib-2.0/include -I /usr/include/atk -I /usr/include/atk-1.0 -I /usr/include/gtk-2.0 -I /usr/include/cairo -I /usr/include/glib-2.0 -I /usr/include/pango-1.0

LIBADD += -lgtk-x11-2.0 -lgdk-x11-2.0 -lYARP_sig -lYARP_sig_logpolar -lYARP_OS

