# Device driver global makefile
include $(YARP_ROOT)/conf/Makefile.template

all: target 

clean:
	+cd ./$(OS)/yarp/; make clean 
	
target:
	+cd ./$(OS)/yarp/; make 

install: 
	+cd ./$(OS)/yarp/; make install
