#!/bin/sh


PROGS="grabber grabber2"

nodes=`netmap | grep -v ":" | grep -v mask | cut -c 1-10 | grep -v "#"`
nodes=`echo $nodes | sed "s/^ *1//"`
echo "Killing processes on nodes$nodes"
for node in $nodes; do
  slay -n$node -Q $* $PROGS
done
