#!/bin/sh

#
# phdbig - dual-screen ph setup
#
# Usage: phdbig n   n is the node number of the secondary display node
#

if [ $# != 1 ]; then
  echo "Usage: " `basename $0` "other-node"
  exit 1
fi

remnid=$1
locnid=$NODE

# switch two desktop LCD's to our nodes
switch 13 $locnid
switch 15 $remnid

# start local Photon
ph

# fake-up what ph would do
export PHOTON=//$locnid/dev/photon
export PHFONT=//$locnid/dev/phfont
export PHOTON_PATH=/qnx4/photon
#export ABLPATH=/qnx4/photon/translations

# start remote display driver
on -f$remnid crttrap -wgo1280,0 start
