#!/bin/sh

FILE=`fullpath -t $0`
OS=qnx
PROCDIR=$YARP_ROOT/bin/$OS

echo "'oly cow..."
echo "be sure you're root..."

#./kill-all

echo "Starting grabber2 on node 3"
on -n3 slay -Q grabber2 
on -d -n3 $PROCDIR/grabber2 -height 128 -width 128 -format bgr -tagged -output /yarp/stereo1/bgr &
sleep 2

#echo "Starting grabber2 on node 18"
#on -n18 slay -Q grabber2 
#on -d -n18 $PROCDIR/grabber2 -height 128 -width 128 -format bgr -tagged -output /pasa/stereo800/bgr &
#sleep 2

echo "Starting left eye..."

on -n7 slay -Q grabber
on -d -n7 $PROCDIR/grabber -height 128 -width 128 -format bgr -tagged -output /yarp/left/wide1 &
on -n2 slay -Q grabber
on -d -n2 $PROCDIR/grabber -height 128 -width 128 -format bgr -tagged -output /yarp/left/wide2 &
on -n9 slay -Q grabber
on -d -n9 $PROCDIR/grabber -height 128 -width 128 -format bgr -tagged -output /yarp/left/fovea1 &
on -n10 slay -Q grabber
on -d -n10 $PROCDIR/grabber -height 128 -width 128 -format bgr -tagged -output /yarp/left/wide3 &
on -n11 slay -Q grabber
on -d -n11 $PROCDIR/grabber -height 128 -width 128 -format bgr -tagged -output /yarp/left/wide4 &

echo "Starting right eye..."

on -n8 slay -Q grabber
on -d -n8 $PROCDIR/grabber -height 128 -width 128 -format bgr -tagged -output /yarp/right/wide1 &
on -n4 slay -Q grabber
on -d -n4 $PROCDIR/grabber -height 128 -width 128 -format bgr -tagged -output /yarp/right/wide2 &
on -n6 slay -Q grabber
on -d -n6 $PROCDIR/grabber -height 128 -width 128 -format bgr -tagged -output /yarp/right/fovea1 &
on -n12 slay -Q grabber
on -d -n12 $PROCDIR/grabber -height 128 -width 128 -format bgr -tagged -output /yarp/right/wide3 &
on -n13 slay -Q grabber
on -d -n13 $PROCDIR/grabber -height 128 -width 128 -format bgr -tagged -output /yarp/right/wide4 &

sleep 3
echo "Allocated channels..."
sin gnames
