#!/bin/sh

echo "starting YARP rogue daemons"

echo "killing old daemons"

slay -n3 -Q meid
slay -n6 -Q meid
slay -n7 -Q meid
slay -n8 -Q ueid
slay -n8 -Q mueid

echo "starting meid on node 3 (torso)"
start-meid-3-320

echo "starting meid on node 6 wrist"
start-meid-6-260

echo "starting meid on node 7 shoulder"
start-meid-7-320

echo "starting ueid on node 8"
start-ueid

echo "starting isd on node 4"
start-isd

echo "starting meid on node 4 (head)"
start-meid-4-320
