#!/bin/sh

###
### Switches and globals
###
###. switches

echo "Hello?"

VERBOSE=0
# TIMING='-timing 120'
TIMING=''
GOTIME='-timing 120'

DNODE=10

if [ -w //$DNODE/dev/photon ]; then
  echo "Photon detected on node $DNODE, using it"
else
  echo "Using photon on node $NODE"
  DNODE=$NODE
fi

cogcam="on -n$DNODE -d cogcam -s //$DNODE/dev/photon"

###
### kill anything else around
###
if $INITIAL_KILL
then
  echo '>>>>>>>>>>>>>>>>>>>STOPPING DUPLICATE PROCESSES'
  ./stopit
fi

on -n13 color_segm $@ &
on -n12 attention $@ &
on -n17 disparity $@ &

let x0=10
let y0=10
let xstep=150
let ystep=300

let x=x0
let y=y0

$cogcam -x $x -y $y +/yarp/view/color_segm/left &
let x=x+xstep
$cogcam -x $x -y $y +/yarp/view/color_segm/right &
let x=x+xstep
$cogcam -x $x -y $y +/yarp/view/color_segm/histo &
let x=x+xstep

$cogcam -x $x -y $y +/yarp/view/disparity/img &
let x=x+xstep
$cogcam -x $x -y $y +/yarp/view/disparity/histo &
let x=x+xstep

$cogcam -x $x -y $y +/yarp/view/saliency &
let x=x+xstep

let x=x0
let y=y+ystep

###
### Left eye attention block
###
if $START_LEFT_EYE_BLOCK
then
  echo '>>>>>>>>>>>>>>>>>STARTING LEFT EYE ATTENTION BLOCK'
   on -n15 visual_attn +/yarp/visual_attn/left $@ &
#cck 
#   on -n19 optic_flow +/yarp/optic_flow/left -p $@ &
   on -n15 skin +/yarp/skin/left $@ &
 
  if $START_LEFT_VIEWER
  then
    $cogcam -x $x -y $y +/yarp/view/visual_attn/left &
    let x=x+xstep
    $cogcam -x $x -y $y +/yarp/view/skin/left &
    let x=x+xstep
#cck
#    $cogcam -x $x -y $y +/yarp/view/motion/left &
#    let x=x+xstep
  fi
fi

###
### Right eye attention block
###
if $START_RIGHT_EYE_BLOCK
then
  echo '>>>>>>>>>>>>>>>>>STARTING RIGHT EYE ATTENTION BLOCK'
  on -n16 visual_attn +/yarp/visual_attn/right $@ &
#cck
#  on -n15 optic_flow +/yarp/optic_flow/right -p $@ &
  on -n16 skin +/yarp/skin/right $@ &
  if $START_RIGHT_VIEWER
  then
    $cogcam -x $x -y $y +/yarp/view/visual_attn/right &
    let x=x+xstep
    $cogcam -x $x -y $y +/yarp/view/skin/right &
    let x=x+xstep
#cck
#    $cogcam -x $x -y $y +/yarp/view/motion/right &
#    let x=x+xstep
  fi
fi


echo '>>>>>>>>>>>>>>>>>>STARTUP DONE'

