#!/bin/sh

###
### Switches and globals
###
###. switches

echo "Hello?"

VERBOSE=0
# TIMING='-timing 120'
TIMING=''
GOTIME='-timing 120'

DNODE=16

if [ -w //$DNODE/dev/photon ]; then
  echo "Photon detected on node $DNODE, using it"
else
  echo "Using photon on node $NODE"
  DNODE=$NODE
fi

cogcam="on -n$DNODE -d cogcam -s //$DNODE/dev/photon"

###
### kill anything else around
###
if $INITIAL_KILL
then
  echo '>>>>>>>>>>>>>>>>>>>STOPPING DUPLICATE PROCESSES'
  ./stopit
fi

#on -n28 color_segm $@ &
on -n22 attention $@ &
on -n14 disparity $@ &

let x0=10
let y0=10
let xstep=150
let ystep=300

let x=x0
let y=y0

$cogcam -x $x -y $y +/yarp/view/disparity/img &
let x=x+xstep
$cogcam -x $x -y $y +/yarp/view/disparity/histo &
let x=x+xstep

$cogcam -x $x -y $y +/yarp/view/saliency &
let x=x+xstep

let x=x0
let y=y+ystep

###
### Left eye attention block
###
if $START_LEFT_EYE_BLOCK
then
  echo '>>>>>>>>>>>>>>>>>STARTING LEFT EYE ATTENTION BLOCK'
   on -n7 visual_attn +/yarp/visual_attn/left $@ &
   on -n2 skin +/yarp/skin/left $@ &
 
  if $START_LEFT_VIEWER
  then
    $cogcam -x $x -y $y +/yarp/view/visual_attn/left &
    let x=x+xstep
    $cogcam -x $x -y $y +/yarp/view/skin/left &
    let x=x+xstep
  fi
fi

###
### Right eye attention block
###
if $START_RIGHT_EYE_BLOCK
then
  echo '>>>>>>>>>>>>>>>>>STARTING RIGHT EYE ATTENTION BLOCK'
  on -n8 visual_attn +/yarp/visual_attn/right $@ &
  on -n4 skin +/yarp/skin/right $@ &
  if $START_RIGHT_VIEWER
  then
    $cogcam -x $x -y $y +/yarp/view/visual_attn/right &
    let x=x+xstep
    $cogcam -x $x -y $y +/yarp/view/skin/right &
    let x=x+xstep
  fi
fi

echo '>>>>>>>>>>>>>>>>>>STARTUP DONE'
