#!/bin/sh

#
# connect finder.
#
porter /scam /yarp/face/i:img
porter /yarp/face/o:img /yarp/viewer/face_finder

#
# connect tracker.
#
porter /yarp/right/wide1 /face_tracker/i:img
porter /face_tracker/o:img /yarp/viewer/face_tracker
porter /yarp/face/o:mix /face_tracker/i:mix
