#!/bin/sh

DNODE=9
OFNODE=26

if [ -w //$DNODE/dev/photon ]; then
  echo "Photon detected on node $DNODE, using it"
else
  echo "Using photon on node $NODE"
  DNODE=$NODE
fi

cogcam="on -n$DNODE -d cogcam -s //$DNODE/dev/photon"

let x0=310
let y0=300
let xstep=150
let ystep=300

let x=x0
let y=y0

$cogcam -x $x -y $y +/yarp/viewer/of/img &
let x=x+xstep
$cogcam -x $x -y $y +/yarp/viewer/of/segmented &
let x=x+xstep
$cogcam -x $x -y $y +/yarp/viewer/armt
let x=x+xstep

slay -n$OFNODE -Q of
on -d -n$OFNODE of
