#!/bin/sh

PROGS="optic_flow skin colorsal motion cogcam color_segm visual_attn attention disparity of face_tracker face_finder attn_tracker obj_segment foveal_egomap egomap"

nodes=`netmap | grep -v ":" | grep -v "mask" | cut -c 1-10 | grep -v "#"`
nodes=`echo $nodes | sed "s/^ *1//"`
echo "Killing processes on nodes$nodes"
for node in $nodes; do
  slay -n$node -Q $PROGS
done
for node in $nodes; do
  slay -9 -n$node -Q $PROGS
done
