#!/bin/sh

echo "starting buggy COG daemons"

slay -n3 -Q meid
slay -n6 -Q meid
slay -n7 -Q meid
slay -n8 -Q ueid

COGBIN=/home/cog/bin

echo "starting meid on node 3 (torso)"
$COGBIN/start-meid-3-320

echo "starting meid on node 6 wrist"
$COGBIN/start-meid-6-260

echo "starting meid on node 7 shoulder"
$COGBIN/start-meid-7-320

echo "starting ueid on node 8"
$COGBIN/start-ueid
