#!/usr/bin/perl -w

use strict;

my $cmd = join(" ", @ARGV);


my $home = `pwd`;
chomp($home);
my @makes = `find . -iname "Makefile"`;

my @dirs = ();
my %slashes;

for my $make (@makes)
{
    chomp($make);
    my $dir = $make;
    $dir =~ s/\/[M|m]akefile$//;
#    if ($dir ne ".")
    {
	my $os = uc(`uname`);
	chomp($os);
	if (!((-e "$dir/DO.NOT.MAKE")||(-e "$dir/DO.NOT.MAKE.$os")))
	{
	    my $slash = $dir;
	    $slash =~ s/[^\/]//g;
#	    print ">>> \"$dir\"  $slash \n";
	    push (@dirs, $dir);
	    $slashes{$dir} = $slash;
	}
    }
}

my @shrinking_dirs = 
    (sort { length($slashes{$b}) <=> length($slashes{$a}) } @dirs);
my @growing_dirs = 
    (sort { length($slashes{$a}) <=> length($slashes{$b}) } @dirs);
#print ">>> @shrinking_dirs\n";
#print ">>> @growing_dirs\n";

for my $dir (@shrinking_dirs)
{
    print "cd $dir\n";
    chdir($dir);
    print "make $cmd\n";
    system "make $cmd\n";
    print "cd $home\n";
    chdir($home);
}






