#!/usr/bin/perl -w

use strict;

my $src = $ENV{"YARP_ROOT"} . "/src/applications/telje/log.txt";

print "Reading from $src\n";

open(SRCFILE,"<$src");

while (<SRCFILE>)
{
    chomp;
    (my $code, my $time, my @arglist) = split(/ /,$_);
    my $codename = `ybc $code`;
    $codename =~ s/[\n\r]//g;
    printf("%8.2f : %-40s", $time, $codename . " ($code)");
    if ($#arglist>=0)
    {
	print " : ", join(" ",@arglist);
    }
    print "\n";
}

close(SRCFILE);
