
ifndef  YARP_ROOT
YARP_ROOT = ../../..
endif

include $(YARP_ROOT)/conf/Makefile.template

CFLAGS += -Wall

MYINCS = -I../include
MYCODELIB = libYARP_OS2

include $(YARP_ROOT)/conf/Makefile.src.template

CFLAGS += -Wall


# DO NOT DELETE

Carriers.o: ../include/yarp/Carriers.h ../include/yarp/String.h
Carriers.o: ../include/yarp/Bytes.h ../include/yarp/Address.h
Carriers.o: ../include/yarp/Face.h ../include/yarp/InputProtocol.h
Carriers.o: ../include/yarp/Route.h ../include/yarp/BlockReader.h
Carriers.o: ../include/yarp/InputStream.h ../include/yarp/OutputStream.h
Carriers.o: ../include/yarp/OutputProtocol.h ../include/yarp/Carrier.h
Carriers.o: ../include/yarp/Logger.h ../include/yarp/TcpFace.h
Carriers.o: ../include/yarp/FakeFace.h
FakeFace.o: ../include/yarp/FakeFace.h ../include/yarp/Face.h
FakeFace.o: ../include/yarp/Address.h ../include/yarp/String.h
FakeFace.o: ../include/yarp/InputProtocol.h ../include/yarp/Route.h
FakeFace.o: ../include/yarp/BlockReader.h ../include/yarp/Bytes.h
FakeFace.o: ../include/yarp/InputStream.h ../include/yarp/OutputStream.h
FakeFace.o: ../include/yarp/Logger.h
Logger.o: ../include/yarp/Logger.h ../include/yarp/String.h
TcpFace.o: ../include/yarp/TcpFace.h ../include/yarp/Face.h
TcpFace.o: ../include/yarp/Address.h ../include/yarp/String.h
TcpFace.o: ../include/yarp/InputProtocol.h ../include/yarp/Route.h
TcpFace.o: ../include/yarp/BlockReader.h ../include/yarp/Bytes.h
TcpFace.o: ../include/yarp/InputStream.h ../include/yarp/OutputStream.h
TcpFace.o: ../include/yarp/Logger.h
Tests.o: ../include/yarp/Address.h ../include/yarp/String.h
Tests.o: ../include/yarp/Carriers.h ../include/yarp/Bytes.h
Tests.o: ../include/yarp/Face.h ../include/yarp/InputProtocol.h
Tests.o: ../include/yarp/Route.h ../include/yarp/BlockReader.h
Tests.o: ../include/yarp/InputStream.h ../include/yarp/OutputStream.h
Tests.o: ../include/yarp/OutputProtocol.h ../include/yarp/Carrier.h
Tests.o: ../include/yarp/StringInputStream.h ../include/yarp/IOException.h
Tests.o: ../include/yarp/StringOutputStream.h
Tests.o: ../include/yarp/FakeTwoWayStream.h ../include/yarp/TwoWayStream.h
Tests.o: ../include/yarp/StreamBlockReader.h ../include/yarp/NetType.h
Tests.o: ../include/yarp/BufferedBlockWriter.h ../include/yarp/BlockWriter.h
Tests.o: ../include/yarp/ManagedBytes.h ../include/yarp/Logger.h
