
ifndef  YARP_ROOT
YARP_ROOT = ../../..
endif

include $(YARP_ROOT)/conf/Makefile.template

CFLAGS += -Wall

MYINCS = -I../include
MYCODELIB = libYARP_OS2

include $(YARP_ROOT)/conf/Makefile.src.template

CFLAGS += -Wall

